// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/todo_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	entity "main/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockITodoUsecase is a mock of ITodoUsecase interface.
type MockITodoUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockITodoUsecaseMockRecorder
}

// MockITodoUsecaseMockRecorder is the mock recorder for MockITodoUsecase.
type MockITodoUsecaseMockRecorder struct {
	mock *MockITodoUsecase
}

// NewMockITodoUsecase creates a new mock instance.
func NewMockITodoUsecase(ctrl *gomock.Controller) *MockITodoUsecase {
	mock := &MockITodoUsecase{ctrl: ctrl}
	mock.recorder = &MockITodoUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITodoUsecase) EXPECT() *MockITodoUsecaseMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockITodoUsecase) CreateTodo(arg0 []byte) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", arg0)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockITodoUsecaseMockRecorder) CreateTodo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockITodoUsecase)(nil).CreateTodo), arg0)
}

// DeleteTodoById mocks base method.
func (m *MockITodoUsecase) DeleteTodoById(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodoById", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodoById indicates an expected call of DeleteTodoById.
func (mr *MockITodoUsecaseMockRecorder) DeleteTodoById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodoById", reflect.TypeOf((*MockITodoUsecase)(nil).DeleteTodoById), arg0)
}

// GetAllTodo mocks base method.
func (m *MockITodoUsecase) GetAllTodo() ([]entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTodo")
	ret0, _ := ret[0].([]entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTodo indicates an expected call of GetAllTodo.
func (mr *MockITodoUsecaseMockRecorder) GetAllTodo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTodo", reflect.TypeOf((*MockITodoUsecase)(nil).GetAllTodo))
}

// GetTodoById mocks base method.
func (m *MockITodoUsecase) GetTodoById(arg0 string) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoById", arg0)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoById indicates an expected call of GetTodoById.
func (mr *MockITodoUsecaseMockRecorder) GetTodoById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoById", reflect.TypeOf((*MockITodoUsecase)(nil).GetTodoById), arg0)
}

// UpdateTodoById mocks base method.
func (m *MockITodoUsecase) UpdateTodoById(arg0 string, arg1 []byte) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodoById", arg0, arg1)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodoById indicates an expected call of UpdateTodoById.
func (mr *MockITodoUsecaseMockRecorder) UpdateTodoById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodoById", reflect.TypeOf((*MockITodoUsecase)(nil).UpdateTodoById), arg0, arg1)
}
