FROM golang:1.22-alpine

RUN mkdir /go/src/app
WORKDIR /go/src/app
COPY ./go/src /go/src/app/

RUN apk update && apk add git \
  && apk add vim

RUN go mod tidy \
  && go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate@latest \
  && go install github.com/cosmtrek/air@latest \
  && go install github.com/golang/mock/mockgen@latest \
  && go get github.com/jinzhu/gorm@latest \
  && go get github.com/golang/mock/gomock@latest \
  && go get github.com/joho/godotenv \
  && go mod tidy \
  && go build

ENV CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64

EXPOSE 8080

CMD ["air"]